---

- name: Ensure required packages are installed.
  apt:
    name: python3-pymysql
  when: mariadb_ensure_requirements

- name: Check if MariaDB is already installed.
  stat:
    path: /etc/init.d/mariadb
  register: _mariadb_installed

- name: Update apt cache if needed and MariaDB is not yet installed.
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  when: not _mariadb_installed.stat.exists

- name: Ensure MariaDB packages are installed.
  apt:
    name: "{{ mariadb_packages }}"
    state: present
  register: mariadb_install_packages_deb

# MariaDB version
- name: Find MariaDB version.
  command: mysql --version
  register: _result_mariadb_version
  changed_when: false

# Because Ubuntu starts MariaDB as part of the install process, we need to stop
# MariaDB and remove the logfiles in case the user set a custom log file size.
# Only do this in versions prior to 10.8.1, otherwise it will no longer be possible
# to start the MariaDB service. See: https://jira.mariadb.org/browse/MDEV-27199
# In current versions, it should not be a problem for the log file to be automatically
# resized when the log file size is changed, followed by a service restart.
- name: Block after installation
  when:
    - not _mariadb_installed.stat.exists
    - ( _result_mariadb_version.stdout | regex_findall('(\d+\.\d+\.\d+)-MariaDB') |
      first | default('999') ) is version('10.8.1', '<')
  block:

    - name: Ensure MariaDB is stopped after initial install.
      service:
        name: "{{ mariadb_daemon }}"
        state: stopped

    - name: Delete innodb log files created by apt package after initial install.
      file:
        path: "{{ (mariadb_datadir, item) | path_join }}"
        state: absent
      with_items:
        - ib_logfile0
        - ib_logfile1
